port: 8000

blocksPath: /iitkbucks/blocks
frontendPath: /iitkbucks/frontend

myUrl: "http://localhost:8000"
myPublicKeyFile: "/iitkbucks/my_public.pem"

isPro: true
initialTarget: "00000f0000000000000000000000000000000000000000000000000000000000"
initialBlockReward: 10000

logLevel: 4

maxPeers: 5
potentialPeers:
  - "https://iitkbucks.pclub.in"
